Ai_Cortex:
  target: dev
  outputs:
    dev:
      type: snowflake

      account: "{{ env_var('SF_ACCOUNT', 'false') }}"
      user: "{{ env_var('SF_USER', 'false') }}"
      password: "{{ env_var('SF_PASSWORD', 'false') }}"
      role: "{{ env_var('SF_ROLE', 'false') }}"
      database: "{{ env_var('SF_DATABASE', 'false') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'false') }}"
      schema: "{{ env_var('SF_SCHEMA', 'false') }}"
      threads: "{{ env_var('SF_THREADS', '8') }}"
      client_session_keep_alive: "{{ env_var('SF_KEEP_ALIVE', 'false') }}"
